### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mih** [duanchiheihei/studyforrest_denoise#1]
I just wanted to thank you for putting https://github.com/OpenNeuroDatasets/ds001769 together and releasing it publicly, for using DataLad, and for releasing the code in here! 

This is a fantastic contribution to the studyforrest project. I have forked the dataset as
https://github.com/psychoinformatics-de/studyforrest-data-phase2-denoised to have it listed alongside the other available datasets at https://github.com/psychoinformatics-de?utf8=%E2%9C%93&q=studyforrest-data

Thx much!

**Comment by xingyu-liu** [comment]
Hi Michael,
sorry for such a long long delay! I have no clue why I missed this message before. 

Thank you for establishing the whole studyforrest project. It's a treasure with multimodal neural and behavial data. Glad to have the chance to get involved.

Merry christmas in advance!
Xingyu
